x-flying-bot: &flying-bot
  build: .
  image: flying-bot
  restart: unless-stopped

services:
  steel:
    image: steel:latest
    volumes:
      - ../config:/steel/config
      - ../saves:/steel/saves
    ports:
      - 25565:25565

  south_overworld:
    <<: *flying-bot
    command: ["0.0", "overworld", "steel", "fb_south_over"]
  east_overworld:
    <<: *flying-bot
    command: ["-90.0", "overworld", "steel", "fb_east_over"]
  north_overworld:
    <<: *flying-bot
    command: ["180.0", "overworld", "steel", "fb_north_over"]
  west_overworld:
    <<: *flying-bot
    command: ["90.0", "overworld", "steel", "fb_west_over"]

  south_nether:
    <<: *flying-bot
    command: ["0.0", "nether", "steel", "fb_south_nether"]
  east_nether:
    <<: *flying-bot
    command: ["-90.0", "nether", "steel", "fb_east_nether"]
  north_nether:
    <<: *flying-bot
    command: ["180.0", "nether", "steel", "fb_north_nether"]
  west_nether:
    <<: *flying-bot
    command: ["90.0", "nether", "steel", "fb_west_nether"]

  south_end:
    <<: *flying-bot
    command: ["0.0", "end", "steel", "fb_south_end"]
  east_end:
    <<: *flying-bot
    command: ["-90.0", "end", "steel", "fb_east_end"]
  north_end:
    <<: *flying-bot
    command: ["180.0", "end", "steel", "fb_north_end"]
  west_end:
    <<: *flying-bot
    command: ["90.0", "end", "steel", "fb_west_end"]
