x-flying-bot: &flying-bot
  build: .
  image: flying-bot
  restart: unless-stopped

services:
  steel:
    image: steel:latest
    volumes:
      - ../config:/steel/config
      - ../saves:/steel/saves
    ports:
      - 25565:25565

  south_overworld:
    <<: *flying-bot
    command: ["0.0", "overworld", "steel", "flying_bot_south_overworld"]
  east_overworld:
    <<: *flying-bot
    command: ["-90.0", "overworld", "steel", "flying_bot_east_overworld"]
  north_overworld:
    <<: *flying-bot
    command: ["180.0", "overworld", "steel", "flying_bot_north_overworld"]
  west_overworld:
    <<: *flying-bot
    command: ["90.0", "overworld", "steel", "flying_bot_west_overworld"]

  south_nether:
    <<: *flying-bot
    command: ["0.0", "nether", "steel", "flying_bot_south_nether"]
  east_nether:
    <<: *flying-bot
    command: ["-90.0", "nether", "steel", "flying_bot_east_nether"]
  north_nether:
    <<: *flying-bot
    command: ["180.0", "nether", "steel", "flying_bot_north_nether"]
  west_nether:
    <<: *flying-bot
    command: ["90.0", "nether", "steel", "flying_bot_west_nether"]

  south_end:
    <<: *flying-bot
    command: ["0.0", "end", "steel", "flying_bot_south_end"]
  east_end:
    <<: *flying-bot
    command: ["-90.0", "end", "steel", "flying_bot_east_end"]
  north_end:
    <<: *flying-bot
    command: ["180.0", "end", "steel", "flying_bot_north_end"]
  west_end:
    <<: *flying-bot
    command: ["90.0", "end", "steel", "flying_bot_west_end"]
